CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Gender" integer NOT NULL,
    "Avatar" text NOT NULL,
    "Phone" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "ModificationTime" timestamp with time zone NULL,
    "CreatorID" integer NULL,
    "ModifyUserID" integer NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "ScheduleReserveCustomer" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "EstimatedArrivalTime" timestamp with time zone NOT NULL,
    "ReserveTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ScheduleReserveCustomer" PRIMARY KEY ("Id")
);

CREATE TABLE "Technicians" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Gender" integer NOT NULL,
    "Avatar" text NOT NULL,
    "ContactInfo_Email" text NOT NULL,
    "ContactInfo_Phone" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "ModificationTime" timestamp with time zone NULL,
    "CreatorID" integer NULL,
    "ModifyUserID" integer NULL,
    CONSTRAINT "PK_Technicians" PRIMARY KEY ("Id")
);

CREATE TABLE "MassageSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TechnicianId" integer NOT NULL,
    "WorkTime_StartTime" timestamp with time zone NOT NULL,
    "WorkTime_EndTime" timestamp with time zone NOT NULL,
    "ReserveCustomerId" integer NULL,
    "State" integer NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "ModificationTime" timestamp with time zone NULL,
    "CreatorID" integer NULL,
    "ModifyUserID" integer NULL,
    CONSTRAINT "PK_MassageSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MassageSchedules_ScheduleReserveCustomer_ReserveCustomerId" FOREIGN KEY ("ReserveCustomerId") REFERENCES "ScheduleReserveCustomer" ("Id")
);

CREATE INDEX "IX_MassageSchedules_ReserveCustomerId" ON "MassageSchedules" ("ReserveCustomerId");

CREATE INDEX "IX_ScheduleReserveCustomer_CustomerId" ON "ScheduleReserveCustomer" ("CustomerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211205140318_Init', '6.0.0');

COMMIT;

